package FontSide;

import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Imperfeton
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public static boolean isLogin = false;
    public static boolean isManager = false;
    public static User currentUser;
    
    public MainPage() throws NoSuchAlgorithmException, SQLException {
        initComponents();
        setupDatabase();
        bntOrderProduct.setVisible(isManager);
        bntLogout.setVisible(isLogin);
        bntSignUp.setVisible(!isLogin);
        bntLogin.setVisible(!isLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BntOrderMeal = new javax.swing.JButton();
        bntLogin = new javax.swing.JButton();
        bntSignUp = new javax.swing.JButton();
        bntOrderProduct = new javax.swing.JButton();
        bntLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        jLabel1.setText("Yummi Pizza");

        BntOrderMeal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BntOrderMeal.setText("Order Meal");
        BntOrderMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderMealActionPerformed(evt);
            }
        });

        bntLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bntLogin.setText("Login");
        bntLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLoginActionPerformed(evt);
            }
        });

        bntSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bntSignUp.setText("SignUp");
        bntSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSignUpActionPerformed(evt);
            }
        });

        bntOrderProduct.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        bntOrderProduct.setText("Order Product");

        bntLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bntLogout.setText("Log out");
        bntLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bntLogout)
                        .addGap(82, 82, 82)
                        .addComponent(bntLogin)
                        .addGap(44, 44, 44)
                        .addComponent(bntSignUp)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225))))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntOrderProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntOrderMeal, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(BntOrderMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bntOrderProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntSignUp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntLogin)
                        .addComponent(bntLogout)))
                .addGap(61, 61, 61))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntOrderMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderMealActionPerformed
        dispose();
        OrderMealPage oderMealPage = new OrderMealPage();
        oderMealPage.setVisible(true);
        Cart.ListOfProduct = new ArrayList<>();
    }//GEN-LAST:event_BntOrderMealActionPerformed

    private void bntSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSignUpActionPerformed
        RegisterPage loginPage = new RegisterPage();
        loginPage.setVisible(true);
    }//GEN-LAST:event_bntSignUpActionPerformed

    private void bntLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLoginActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_bntLoginActionPerformed

    private void bntLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogoutActionPerformed
        dispose();
        isLogin = false;
        isManager = false;
        currentUser = null;
        MainPage mainPage;
        try {
            mainPage = new MainPage();
            mainPage.setVisible(true);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainPage().setVisible(true);
                    
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private static void setupDatabase() throws SQLException, NoSuchAlgorithmException {
        SaveData.setupDatabase();
        //create admin with full permission
        if(!isUserExist("admin@gmail.com")){
            User admin = new User("admin","admin","admin@gmail.com","","admin","manager");
            SaveData.saveNewUser(admin);
        }
    }
    
    public static boolean isUserExist(String userEmail) throws SQLException {
        ArrayList<String> userEmails = GetData.getUserEmails();
        return userEmails.contains(userEmail);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntOrderMeal;
    public static javax.swing.JButton bntLogin;
    public static javax.swing.JButton bntLogout;
    public static javax.swing.JButton bntOrderProduct;
    public static javax.swing.JButton bntSignUp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
