package FontSide;

import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Imperfeton
 */
public class OrderMealPage extends javax.swing.JFrame {

    /**
     * Creates new form OrderMealPage
     */
    public OrderMealPage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelOderMeal = new javax.swing.JButton();
        tabFood = new javax.swing.JTabbedPane();
        TabPizza = new javax.swing.JScrollPane();
        scrollPizza = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BntOrderSupremePizza = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BntOrderChickenPizza = new javax.swing.JButton();
        BntOrderSausagePizza = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BntOrderHawaiianPizza = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BntOrderVeggieLoversPizza = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TabPasta = new javax.swing.JScrollPane();
        scollPasta = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        BntOrderCreamyMushroomPasta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BntOrderClassBolognesePasta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        TabBevarage = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        BntOrderCoke = new javax.swing.JButton();
        BntOrderPepsi = new javax.swing.JButton();
        BntOrderSolo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BntOrderOrangeJuice = new javax.swing.JButton();
        BntOrderMangoJuice = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BntCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        CancelOderMeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CancelOderMeal.setText("Cancel");
        CancelOderMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOderMealActionPerformed(evt);
            }
        });

        tabFood.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        TabPizza.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TabPizza.setMaximumSize(new java.awt.Dimension(900, 800));

        scrollPizza.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPizza.setMaximumSize(new java.awt.Dimension(900, 785));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 900));

        jLabel1.setText("Supreme Pizza");

        BntOrderSupremePizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\supreme pizza.png")); // NOI18N
        BntOrderSupremePizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderSupremePizzaActionPerformed(evt);
            }
        });

        jLabel2.setText("Chicken Pizza");

        BntOrderChickenPizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\chicken pizza.png")); // NOI18N
        BntOrderChickenPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderChickenPizzaActionPerformed(evt);
            }
        });

        BntOrderSausagePizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\rsz_sausage_pizza.png")); // NOI18N
        BntOrderSausagePizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderSausagePizzaActionPerformed(evt);
            }
        });

        jLabel3.setText("Sausage Pizza");

        BntOrderHawaiianPizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\rsz_11rsz_hawaiian.png")); // NOI18N
        BntOrderHawaiianPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderHawaiianPizzaActionPerformed(evt);
            }
        });

        jLabel4.setText("Hawaiian Pizza");

        BntOrderVeggieLoversPizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\veggie lovers.png")); // NOI18N
        BntOrderVeggieLoversPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderVeggieLoversPizzaActionPerformed(evt);
            }
        });

        jLabel5.setText("Veggie Lovers Pizza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BntOrderVeggieLoversPizza)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BntOrderSupremePizza)
                                .addComponent(BntOrderSausagePizza)))
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BntOrderChickenPizza)
                            .addComponent(BntOrderHawaiianPizza)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel5)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BntOrderSupremePizza)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(BntOrderSausagePizza))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BntOrderChickenPizza)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BntOrderHawaiianPizza)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(73, 73, 73)
                .addComponent(BntOrderVeggieLoversPizza)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        scrollPizza.setViewportView(jPanel1);

        TabPizza.setViewportView(scrollPizza);

        tabFood.addTab("Pizza", TabPizza);

        TabPasta.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        scollPasta.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        BntOrderCreamyMushroomPasta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\rsz_1rsz_creamy_mushroom.png")); // NOI18N
        BntOrderCreamyMushroomPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderCreamyMushroomPastaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Creamy Mushroom Pasta");

        BntOrderClassBolognesePasta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\classBolognese.png")); // NOI18N
        BntOrderClassBolognesePasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderClassBolognesePastaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Classic Bolognese Pasta");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setText("A slippery tangle of pasta bathed in a \ncreamy parmesan sauce loaded with buttery\ngarlic mushrooms");
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(4);
        jTextArea2.setText("This classic Italian sauce simmers \nfor hours to develop maximum flavor. \nMade with a blend of ground beef, \npork, and Italian sausage, it's great with fresh pasta.");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(BntOrderCreamyMushroomPasta)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel7)))
                        .addGap(80, 80, 80)
                        .addComponent(BntOrderClassBolognesePasta)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BntOrderCreamyMushroomPasta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(BntOrderClassBolognesePasta)))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        scollPasta.setViewportView(jPanel2);

        TabPasta.setViewportView(scollPasta);

        tabFood.addTab("Pasta", TabPasta);

        TabBevarage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TabBevarage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        BntOrderCoke.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\coke.png")); // NOI18N
        BntOrderCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderCokeActionPerformed(evt);
            }
        });

        BntOrderPepsi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\rsz_1pepsi.png")); // NOI18N
        BntOrderPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderPepsiActionPerformed(evt);
            }
        });

        BntOrderSolo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\rsz_solo.png")); // NOI18N
        BntOrderSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderSoloActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setText("Soft drinks");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Juices");

        BntOrderOrangeJuice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\orange juice.png")); // NOI18N
        BntOrderOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderOrangeJuiceActionPerformed(evt);
            }
        });

        BntOrderMangoJuice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\rsz_1mango_juice.png")); // NOI18N
        BntOrderMangoJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntOrderMangoJuiceActionPerformed(evt);
            }
        });

        jLabel10.setText("Coke");

        jLabel11.setText("Pepsi");

        jLabel12.setText("Solo");

        jLabel13.setText("Orange Juice");

        jLabel14.setText("Mango Juice");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(BntOrderOrangeJuice)
                        .addGap(166, 166, 166)
                        .addComponent(BntOrderMangoJuice)))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(BntOrderCoke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BntOrderPepsi)
                .addGap(127, 127, 127)
                .addComponent(BntOrderSolo)
                .addGap(107, 107, 107))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(246, 246, 246))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel10)
                .addGap(216, 216, 216)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(162, 162, 162))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BntOrderSolo)
                    .addComponent(BntOrderCoke)
                    .addComponent(BntOrderPepsi))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(BntOrderOrangeJuice))
                            .addComponent(BntOrderMangoJuice)))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        TabBevarage.setViewportView(jScrollPane3);

        tabFood.addTab("Bevarage", TabBevarage);

        BntCart.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BntCart.setForeground(new java.awt.Color(204, 0, 0));
        BntCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxsys\\Documents\\NetBeansProjects\\32555Assignment\\src\\main\\java\\Food\\cart.png")); // NOI18N
        BntCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tabFood, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CancelOderMeal)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BntCart)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(BntCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabFood, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CancelOderMeal)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelOderMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOderMealActionPerformed
        dispose();
    }//GEN-LAST:event_CancelOderMealActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainPage mainPage = null;
        try {
            mainPage = new MainPage();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(OrderMealPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderMealPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPage.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void BntOrderSupremePizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderSupremePizzaActionPerformed
        AddPizza addProductPage = new AddPizza();
        AddPizza.lableFoodName.setText(OrderMealPage.jLabel1.getText());
        AddPizza.lableFoodImage.setIcon(OrderMealPage.BntOrderSupremePizza.getIcon());
        AddPizza.lableFoodImage.setText("");
        try{
            Integer price = GetData.getPizzaPrice("supreme", 8);
            AddPizza.lableTotal.setText(price.toString() + " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addProductPage.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderSupremePizzaActionPerformed

    private void BntOrderChickenPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderChickenPizzaActionPerformed
        AddPizza addProductPage = new AddPizza();
        AddPizza.lableFoodName.setText(OrderMealPage.jLabel2.getText());
        AddPizza.lableFoodImage.setIcon(OrderMealPage.BntOrderChickenPizza.getIcon());
        AddPizza.lableFoodImage.setText("");
        try{
            Integer price = GetData.getPizzaPrice("chicken", 8);
            AddPizza.lableTotal.setText(price.toString() + " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addProductPage.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderChickenPizzaActionPerformed

    private void BntOrderCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderCokeActionPerformed
        AddDrink addDrinks = new AddDrink();
        AddDrink.labelDrinkName.setText(OrderMealPage.jLabel10.getText());
        AddDrink.labelDrinkImage.setIcon(OrderMealPage.BntOrderCoke.getIcon());
        AddDrink.labelDrinkImage.setText("");
        try{
            Integer price = GetData.getDrinkPrice("coke");
            AddDrink.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addDrinks.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderCokeActionPerformed

    private void BntOrderSausagePizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderSausagePizzaActionPerformed
        AddPizza addProductPage = new AddPizza();
        AddPizza.lableFoodName.setText(OrderMealPage.jLabel3.getText());
        AddPizza.lableFoodImage.setIcon(OrderMealPage.BntOrderSausagePizza.getIcon());
        AddPizza.lableFoodImage.setText("");
        try{
            Integer price = GetData.getPizzaPrice("sausage", 8);
            AddPizza.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addProductPage.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderSausagePizzaActionPerformed

    private void BntOrderHawaiianPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderHawaiianPizzaActionPerformed
        AddPizza addProductPage = new AddPizza();
        AddPizza.lableFoodName.setText(OrderMealPage.jLabel4.getText());
        AddPizza.lableFoodImage.setIcon(OrderMealPage.BntOrderHawaiianPizza.getIcon());
        AddPizza.lableFoodImage.setText("");
        try{
            Integer price = GetData.getPizzaPrice("hawaiian", 8);
            AddPizza.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addProductPage.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderHawaiianPizzaActionPerformed

    private void BntOrderVeggieLoversPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderVeggieLoversPizzaActionPerformed
        AddPizza addProductPage = new AddPizza();
        AddPizza.lableFoodName.setText(OrderMealPage.jLabel5.getText());
        AddPizza.lableFoodImage.setIcon(OrderMealPage.BntOrderVeggieLoversPizza.getIcon());
        AddPizza.lableFoodImage.setText("");
        try{
            Integer price = GetData.getPizzaPrice("veggie", 8);
            AddPizza.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addProductPage.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderVeggieLoversPizzaActionPerformed

    private void BntOrderCreamyMushroomPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderCreamyMushroomPastaActionPerformed
        AddPasta addPasta = new AddPasta();
        AddPasta.labelPastaName.setText(OrderMealPage.jLabel6.getText());
        AddPasta.labelPastaImage.setIcon(OrderMealPage.BntOrderCreamyMushroomPasta.getIcon());
        AddPasta.labelPastaImage.setText("");
        try{
            Integer price = GetData.getPastaPrice("creamy");
            AddPasta.labelTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addPasta.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderCreamyMushroomPastaActionPerformed

    private void BntOrderClassBolognesePastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderClassBolognesePastaActionPerformed
        AddPasta addPasta = new AddPasta();
        AddPasta.labelPastaName.setText(OrderMealPage.jLabel7.getText());
        AddPasta.labelPastaImage.setIcon(OrderMealPage.BntOrderClassBolognesePasta.getIcon());
        AddPasta.labelPastaImage.setText("");
        try{
            Integer price = GetData.getPastaPrice("bolognese");
            AddPasta.labelTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addPasta.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderClassBolognesePastaActionPerformed

    private void BntOrderPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderPepsiActionPerformed
        AddDrink addDrinks = new AddDrink();
        AddDrink.labelDrinkName.setText(OrderMealPage.jLabel11.getText());
        AddDrink.labelDrinkImage.setIcon(OrderMealPage.BntOrderPepsi.getIcon());
        AddDrink.labelDrinkImage.setText("");
        try{
            Integer price = GetData.getDrinkPrice("pepsi");
            AddDrink.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addDrinks.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderPepsiActionPerformed

    private void BntOrderSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderSoloActionPerformed
        AddDrink addDrinks = new AddDrink();
        AddDrink.labelDrinkName.setText(OrderMealPage.jLabel12.getText());
        AddDrink.labelDrinkImage.setIcon(OrderMealPage.BntOrderSolo.getIcon());
        AddDrink.labelDrinkImage.setText("");
        try{
            Integer price = GetData.getDrinkPrice("solo");
            AddDrink.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addDrinks.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderSoloActionPerformed

    private void BntOrderOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderOrangeJuiceActionPerformed
        AddDrink addDrinks = new AddDrink();
        AddDrink.labelDrinkName.setText(OrderMealPage.jLabel13.getText());
        AddDrink.labelDrinkImage.setIcon(OrderMealPage.BntOrderOrangeJuice.getIcon());
        AddDrink.labelDrinkImage.setText("");
        try{
            Integer price = GetData.getDrinkPrice("orange_juice");
            AddDrink.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addDrinks.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderOrangeJuiceActionPerformed

    private void BntOrderMangoJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntOrderMangoJuiceActionPerformed
        AddDrink addDrinks = new AddDrink();
        AddDrink.labelDrinkName.setText(OrderMealPage.jLabel14.getText());
        AddDrink.labelDrinkImage.setIcon(OrderMealPage.BntOrderMangoJuice.getIcon());
        AddDrink.labelDrinkImage.setText("");
        try{
            Integer price = GetData.getDrinkPrice("mango_juice");
            AddDrink.lableTotal.setText(price.toString()+ " $");
        }catch(SQLException ex){
            System.out.print(ex);
        }
        addDrinks.setVisible(true);
        hide();
    }//GEN-LAST:event_BntOrderMangoJuiceActionPerformed

    private void BntCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntCartActionPerformed
        CartPage cartPage = new CartPage();
        cartPage.setVisible(true);
        hide();
    }//GEN-LAST:event_BntCartActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderMealPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderMealPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderMealPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderMealPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderMealPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntCart;
    public static javax.swing.JButton BntOrderChickenPizza;
    public static javax.swing.JButton BntOrderClassBolognesePasta;
    public static javax.swing.JButton BntOrderCoke;
    public static javax.swing.JButton BntOrderCreamyMushroomPasta;
    public static javax.swing.JButton BntOrderHawaiianPizza;
    public static javax.swing.JButton BntOrderMangoJuice;
    public static javax.swing.JButton BntOrderOrangeJuice;
    public static javax.swing.JButton BntOrderPepsi;
    public static javax.swing.JButton BntOrderSausagePizza;
    public static javax.swing.JButton BntOrderSolo;
    public static javax.swing.JButton BntOrderSupremePizza;
    public static javax.swing.JButton BntOrderVeggieLoversPizza;
    private javax.swing.JButton CancelOderMeal;
    private javax.swing.JScrollPane TabBevarage;
    private javax.swing.JScrollPane TabPasta;
    private javax.swing.JScrollPane TabPizza;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static transient javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JScrollPane scollPasta;
    private javax.swing.JScrollPane scrollPizza;
    private javax.swing.JTabbedPane tabFood;
    // End of variables declaration//GEN-END:variables
}
